[
  # Ignore test errors (since CI runs in test env)
  {"test/support/channel_case.ex:1:unknown_function Function ExUnit.Callbacks.__merge__/3 does not exist."},
  {"test/support/channel_case.ex:20:unknown_function Function ExUnit.CaseTemplate.__proxy__/2 does not exist."},
  {"test/support/conn_case.ex:1:unknown_function Function ExUnit.Callbacks.__merge__/3 does not exist."},
  {"test/support/conn_case.ex:20:unknown_function Function ExUnit.CaseTemplate.__proxy__/2 does not exist."},
  {"test/support/data_case.ex:19:unknown_function Function ExUnit.CaseTemplate.__proxy__/2 does not exist."},
  {"test/support/data_case.ex:1:unknown_function Function ExUnit.Callbacks.__merge__/3 does not exist."}
]
